"""add_remaining_sovereign_models_and_tenant_fields

Revision ID: acb214682119
Revises: 93f1d02cce3c
Create Date: 2026-09-21 13:28:37.744100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acb214682119'
down_revision: Union[str, Sequence[str], None] = '93f1d02cce3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_templates',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('default_tools', sa.JSON(), nullable=False),
    sa.Column('default_model_id', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=False),
    sa.Column('max_steps', sa.Integer(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_templates'))
    )
    op.create_table('connectors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('auth_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_connectors'))
    )
    with op.batch_alter_table('connectors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_connectors_is_enabled'), ['is_enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_connectors_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_connectors_type'), ['type'], unique=False)

    op.create_table('agents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('model_id', sa.String(length=100), nullable=False),
    sa.Column('tool_allowlist', sa.JSON(), nullable=False),
    sa.Column('max_steps', sa.Integer(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_agents_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agents'))
    )
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agents_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_agents_name'), ['name'], unique=False)

    op.create_table('connector_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('connector_id', sa.String(length=36), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=True),
    sa.Column('allowed_endpoints', sa.JSON(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('network_policy', sa.String(length=50), nullable=False),
    sa.Column('headers_masked', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.id'], name=op.f('fk_connector_configs_connector_id_connectors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_connector_configs'))
    )
    with op.batch_alter_table('connector_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_connector_configs_connector_id'), ['connector_id'], unique=False)

    op.create_table('connector_health',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('connector_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.id'], name=op.f('fk_connector_health_connector_id_connectors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_connector_health'))
    )
    with op.batch_alter_table('connector_health', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_connector_health_connector_id'), ['connector_id'], unique=False)

    op.create_table('connector_permissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('connector_id', sa.String(length=36), nullable=False),
    sa.Column('role_required', sa.String(length=50), nullable=False),
    sa.Column('allowed_actions', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.id'], name=op.f('fk_connector_permissions_connector_id_connectors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_connector_permissions'))
    )
    with op.batch_alter_table('connector_permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_connector_permissions_connector_id'), ['connector_id'], unique=False)

    op.create_table('model_routing_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_prompt', sa.Text(), nullable=False),
    sa.Column('detected_intent', sa.String(length=100), nullable=False),
    sa.Column('required_capabilities', sa.JSON(), nullable=False),
    sa.Column('selected_model_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('execution_time_ms', sa.Float(), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['selected_model_id'], ['model_registry.id'], name=op.f('fk_model_routing_logs_selected_model_id_model_registry'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_model_routing_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_routing_logs'))
    )
    op.create_table('revoked_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_revoked_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_revoked_tokens'))
    )
    with op.batch_alter_table('revoked_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_revoked_tokens_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_revoked_tokens_jti'), ['jti'], unique=False)
        batch_op.create_index(batch_op.f('ix_revoked_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_revoked_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('document_chunks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('chunk_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_chunks_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_chunks'))
    )
    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_chunks_chunk_index'), ['chunk_index'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_chunks_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_chunks_page_number'), ['page_number'], unique=False)

    op.create_table('document_processing_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_processing_logs_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_processing_logs'))
    )
    with op.batch_alter_table('document_processing_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_processing_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_processing_logs_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_processing_logs_stage'), ['stage'], unique=False)

    op.create_table('connector_executions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('connector_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('request_payload', sa.JSON(), nullable=False),
    sa.Column('response_payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.id'], name=op.f('fk_connector_executions_connector_id_connectors'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], name=op.f('fk_connector_executions_run_id_agent_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_connector_executions'))
    )
    with op.batch_alter_table('connector_executions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_connector_executions_connector_id'), ['connector_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_connector_executions_run_id'), ['run_id'], unique=False)

    op.create_table('deliverables',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('company_code', sa.String(length=50), nullable=True),
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_deliverables_approved_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_deliverables_owner_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], name=op.f('fk_deliverables_run_id_agent_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deliverables'))
    )
    with op.batch_alter_table('deliverables', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deliverables_company_code'), ['company_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_deliverables_file_type'), ['file_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_deliverables_filename'), ['filename'], unique=False)
        batch_op.create_index(batch_op.f('ix_deliverables_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deliverables_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deliverables_sha256_hash'), ['sha256_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_deliverables_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_deliverables_title'), ['title'], unique=False)

    op.create_table('execution_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('step_id', sa.String(length=36), nullable=True),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], name=op.f('fk_execution_logs_run_id_agent_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_execution_logs'))
    )
    with op.batch_alter_table('execution_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_execution_logs_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_logs_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_logs_timestamp'), ['timestamp'], unique=False)

    op.create_table('tool_executions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('step_id', sa.String(length=36), nullable=True),
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('execution_time_ms', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('executed_by', sa.String(length=36), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['executed_by'], ['users.id'], name=op.f('fk_tool_executions_executed_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], name=op.f('fk_tool_executions_run_id_agent_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_id'], ['agent_steps.id'], name=op.f('fk_tool_executions_step_id_agent_steps'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tool_executions'))
    )
    with op.batch_alter_table('tool_executions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tool_executions_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tool_executions_tool_name'), ['tool_name'], unique=False)

    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agent_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('company_code', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('plan', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('current_step', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('max_steps', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('error_detail', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_agent_runs_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_company_code'), ['company_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_agent_runs_agent_id_agents'), 'agents', ['agent_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('agent_steps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('safe_summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('error_message', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('correlation_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('company_code', sa.String(length=50), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.create_index(batch_op.f('ix_audit_logs_company_code'), ['company_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_correlation_id'), ['correlation_id'], unique=False)

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_code', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('document_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_conversations_company_code'), ['company_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_document_id'), ['document_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_conversations_document_id_documents'), 'documents', ['document_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vision_applied', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('storage_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('content_preview', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('visual_summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('asset_category', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('processing_error', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('company_code', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_documents_company_code'), ['company_code'], unique=False)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('detected_intent', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('routing_reasoning', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('required_capabilities', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('attachment_name', sa.String(length=255), nullable=True))
        batch_op.alter_column('latency_ms',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)

    with op.batch_alter_table('model_registry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capabilities', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('health_status', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('last_health_check', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('latency_ms', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('error_message', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_default', sa.Boolean(), nullable=False))

    with op.batch_alter_table('model_routing_rules', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_model_routing_rules_target_model_id_model_registry'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_model_routing_rules_target_model_id_model_registry'), 'model_registry', ['target_model_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('tool_registry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('returns_schema', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('permission_required', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('timeout_seconds', sa.Integer(), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('department', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('company_code', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_company_code'), ['company_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_company_code'))
        batch_op.drop_column('company_code')
        batch_op.drop_column('department')
        batch_op.drop_column('role')

    with op.batch_alter_table('tool_registry', schema=None) as batch_op:
        batch_op.drop_column('timeout_seconds')
        batch_op.drop_column('permission_required')
        batch_op.drop_column('returns_schema')

    with op.batch_alter_table('model_routing_rules', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_model_routing_rules_target_model_id_model_registry'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_model_routing_rules_target_model_id_model_registry'), 'model_registry', ['target_model_id'], ['id'], ondelete='RESTRICT')

    with op.batch_alter_table('model_registry', schema=None) as batch_op:
        batch_op.drop_column('is_default')
        batch_op.drop_column('error_message')
        batch_op.drop_column('latency_ms')
        batch_op.drop_column('last_health_check')
        batch_op.drop_column('health_status')
        batch_op.drop_column('capabilities')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('latency_ms',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.drop_column('attachment_name')
        batch_op.drop_column('required_capabilities')
        batch_op.drop_column('routing_reasoning')
        batch_op.drop_column('detected_intent')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_company_code'))
        batch_op.drop_column('company_code')
        batch_op.drop_column('processing_error')
        batch_op.drop_column('asset_category')
        batch_op.drop_column('visual_summary')
        batch_op.drop_column('content_preview')
        batch_op.drop_column('storage_name')
        batch_op.drop_column('vision_applied')

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_conversations_document_id_documents'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_conversations_document_id'))
        batch_op.drop_index(batch_op.f('ix_conversations_company_code'))
        batch_op.drop_column('document_id')
        batch_op.drop_column('company_code')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_correlation_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_company_code'))
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('company_code')
        batch_op.drop_column('correlation_id')

    with op.batch_alter_table('agent_steps', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('error_message')
        batch_op.drop_column('status')
        batch_op.drop_column('safe_summary')
        batch_op.drop_column('title')

    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_agent_runs_agent_id_agents'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_agent_runs_user_id'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_company_code'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_agent_id'))
        batch_op.drop_column('error_detail')
        batch_op.drop_column('max_steps')
        batch_op.drop_column('current_step')
        batch_op.drop_column('plan')
        batch_op.drop_column('company_code')
        batch_op.drop_column('agent_id')

    with op.batch_alter_table('tool_executions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tool_executions_tool_name'))
        batch_op.drop_index(batch_op.f('ix_tool_executions_run_id'))

    op.drop_table('tool_executions')
    with op.batch_alter_table('execution_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_execution_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_execution_logs_run_id'))
        batch_op.drop_index(batch_op.f('ix_execution_logs_event_type'))

    op.drop_table('execution_logs')
    with op.batch_alter_table('deliverables', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deliverables_title'))
        batch_op.drop_index(batch_op.f('ix_deliverables_status'))
        batch_op.drop_index(batch_op.f('ix_deliverables_sha256_hash'))
        batch_op.drop_index(batch_op.f('ix_deliverables_run_id'))
        batch_op.drop_index(batch_op.f('ix_deliverables_owner_id'))
        batch_op.drop_index(batch_op.f('ix_deliverables_filename'))
        batch_op.drop_index(batch_op.f('ix_deliverables_file_type'))
        batch_op.drop_index(batch_op.f('ix_deliverables_company_code'))

    op.drop_table('deliverables')
    with op.batch_alter_table('connector_executions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_connector_executions_run_id'))
        batch_op.drop_index(batch_op.f('ix_connector_executions_connector_id'))

    op.drop_table('connector_executions')
    with op.batch_alter_table('document_processing_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_processing_logs_stage'))
        batch_op.drop_index(batch_op.f('ix_document_processing_logs_document_id'))
        batch_op.drop_index(batch_op.f('ix_document_processing_logs_created_at'))

    op.drop_table('document_processing_logs')
    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_chunks_page_number'))
        batch_op.drop_index(batch_op.f('ix_document_chunks_document_id'))
        batch_op.drop_index(batch_op.f('ix_document_chunks_chunk_index'))

    op.drop_table('document_chunks')
    with op.batch_alter_table('revoked_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_revoked_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_revoked_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_revoked_tokens_jti'))
        batch_op.drop_index(batch_op.f('ix_revoked_tokens_expires_at'))

    op.drop_table('revoked_tokens')
    op.drop_table('model_routing_logs')
    with op.batch_alter_table('connector_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_connector_permissions_connector_id'))

    op.drop_table('connector_permissions')
    with op.batch_alter_table('connector_health', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_connector_health_connector_id'))

    op.drop_table('connector_health')
    with op.batch_alter_table('connector_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_connector_configs_connector_id'))

    op.drop_table('connector_configs')
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agents_name'))
        batch_op.drop_index(batch_op.f('ix_agents_category'))

    op.drop_table('agents')
    with op.batch_alter_table('connectors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_connectors_type'))
        batch_op.drop_index(batch_op.f('ix_connectors_name'))
        batch_op.drop_index(batch_op.f('ix_connectors_is_enabled'))

    op.drop_table('connectors')
    op.drop_table('agent_templates')
    # ### end Alembic commands ###
